const express=require('express')
const router=express.Router()
const userController=require("../controllers/user.controller")
const doctorController=require("../controllers/doctor.controller")
const forgetpasswordController=require("../controllers/forgetpassword.controller")
router.get('/',userController.LandingPage)
router.post('/signup',userController.Signup)
router.post('/docsignup',doctorController.Signup)
router.post('/login',userController.Login)
router.post('/doclogin',doctorController.Login)
router.post('/forgetpassword',forgetpasswordController.forgetEmail)
router.post('/resetPassword',forgetpasswordController.resetPassword)
router.post('/resetpassword2',userController.resetPassword)
router.post('/checkpassword',userController.checkPassword)
router.get('/alldocs',doctorController.allDoctors)
router.get('/doctor',doctorController.presentDoctor)
router.get('/allpats',userController.allPatients)
router.get('/patient',userController.presentPatient)
module.exports=router