const express=require('express')
const router=express.Router()
const userController=require("../controllers/user.controller")
const doctorController=require("../controllers/doctor.controller")
router.get('/',userController.LandingPage)
router.post('/signup',userController.Signup)
router.post('/docsignup',doctorController.Signup)
router.post('/login',userController.Login)
router.post('/doclogin',doctorController.Login)
router.get('/alldocs',doctorController.allDoctors)
router.get('/doctor',doctorController.presentDoctor)
module.exports=router